### ISSUE TITLE
Examples returning JSON decode error

### ISSUE THREAD

**Issue by bertrandclim** [ESGF/esgf-pyclient#110]
Any query I try fails with a JSONDecodeError (with or without facets specified, from the examples, or of my own making). For example,
```python
from pyesgf.search import SearchConnection
conn = SearchConnection('https://aims2.llnl.gov' distrib=False)
ctx = conn.new_context(facets='project,experiment_id,variable_id,frequency',
    project = 'CMIP6',
    experiment='amip',
    variable='rlds',
    time_frequency='subhrPt'
    ))
```
returns something like:
```python
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File /projects/$USER/envs/sci3/lib/python3.12/site-packages/requests/models.py:974, in Response.json(self, **kwargs)
    973 try:
--> 974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /projects/$USER/envs/sci3/lib/python3.12/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File /projects/$USER/envs/sci3/lib/python3.12/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File /projects/$USER/envs/sci3/lib/python3.12/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
File <timed exec>:4

File /projects/$USER/envs/sci3/lib/python3.12/site-packages/pyesgf/search/context.py:182, in SearchContext.hit_count(self)
    180 @property
    181 def hit_count(self):
--> 182     self.__update_counts()
    183     return self.__hit_count

File /projects/$USER/envs/sci3/lib/python3.12/site-packages/pyesgf/search/context.py:220, in SearchContext.__update_counts(self)
    217     if self.connection.distrib:
    218         self._do_facets_star_warning()
--> 220 response = self.connection.send_search(query_dict, limit=0)
    221 for facet, counts in (list(response['facet_counts']['facet_fields'].items())):
    222     d = self.__facet_counts[facet] = {}

File /projects/$USER/envs/sci3/lib/python3.12/site-packages/pyesgf/search/connection.py:160, in SearchConnection.send_search(self, query_dict, limit, offset, shards)
    158     self.open()
    159 response = self._send_query('search', full_query)
--> 160 ret = response.json()
    161 response.close()
    162 self.close()

File /projects/$USER/envs/sci3/lib/python3.12/site-packages/requests/models.py:978, in Response.json(self, **kwargs)
    974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 978     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Here is my environment configuration:
```yml
name: esgf-issue
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attr=2.5.1
  - attrs=25.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - azure-storage-files-datalake-cpp=12.10.0
  - blosc=1.21.6
  - bokeh=3.5.0
  - bottleneck=1.4.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.1
  - ca-certificates=2025.1.31
  - cairo=1.18.0
  - cartopy=0.23.0
  - cattrs=24.1.2
  - certifi=2025.1.31
  - cffi=1.16.0
  - cftime=1.6.4
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.1
  - cryptography=42.0.8
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.7.0
  - dask-core=2024.7.0
  - dask-expr=1.1.7
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.7.0
  - esgf-pyclient=0.3.1
  - exceptiongroup=1.2.2
  - executing=0.8.3
  - expat=2.6.2
  - flexcache=0.3
  - flexparser=0.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fortranformat=2.0.0
  - freetype=2.12.1
  - fsspec=2024.6.1
  - geos=3.12.2
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - glib=2.80.3
  - glib-tools=2.80.3
  - glog=0.7.1
  - graphite2=1.3.13
  - gst-plugins-base=1.24.5
  - gstreamer=1.24.5
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - iniconfig=2.0.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - itsdangerous=2.2.0
  - jedi=0.18.1
  - jinja2=3.1.4
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - legacy-cgi=2.6.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.8.0
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=255
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.6
  - metpy=1.6.3
  - mpg123=1.32.6
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - myproxyclient=2.1.1
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.1
  - nspr=4.35
  - nss=3.102
  - numpy=2.0.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.3
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.8.0
  - pillow=10.4.0
  - pint=0.24.3
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.8.2
  - proj=9.4.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pygments=2.15.1
  - pyhdf=0.11.4
  - pyopenssl=25.0.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt-main=5.15.8
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - requests-cache=1.2.1
  - s2n=1.4.17
  - scipy=1.14.0
  - setuptools=70.3.0
  - shapely=2.0.5
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sqlite=3.46.0
  - stack_data=0.2.0
  - tblib=3.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ujson=5.10.0
  - url-normalize=1.4.3
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - webob=1.8.9
  - wheel=0.43.0
  - xarray=2024.6.0
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
```
